# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - bodyclose
    - dogsled
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - nakedret
    - nolintlint
    - revive
    - stylecheck
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.Unmarshal
      - (*encoding/json.Encoder).Encode
      - (*encoding/json.Decoder).Decode
      - (net/http.ResponseWriter).Write
      - (*database/sql.Tx).Rollback

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gocyclo:
    min-complexity: 50

  goconst:
    min-len: 3
    min-occurrences: 5

  misspell:
    locale: US

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf

  gocritic:
    disabled-checks:
      - exitAfterDefer

  gosec:
    excludes:
      - G104
      - G107

  stylecheck:
    checks:
      - all
      - -ST1000
      - -ST1003

  nakedret:
    max-func-lines: 50

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - errcheck
        - gocritic
        - noctx
        - gochecknoinits

    - path: \.gen\.go
      linters:
        - all

    # Ignore deprecated OPA packages for now
    - path: internal/policy/
      linters:
        - staticcheck
      text: "SA1019"

    # Allow "cancelled" spelling (British English is valid)
    - linters:
        - misspell
      text: "cancelled"

  max-issues-per-linter: 50
  max-same-issues: 5

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
